default_provider = "age"

[providers.age]
type = "age"
recipients = ["age1y6z5twxvg2rv40j8q8323yke6scxrtewl8e92l5dkjm75z75cscshvgrgg"]

[secrets]
GITLAB_USERNAME= { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4REh3WTBOTG9rVGVFRDVUK1BORnU2elJhNkZ2RGw4YW5oazV5NVV5cEFjCmhGRk0rVW9oZUMvVEtVVDdwTjNRbEU1M2VBQTJIdG5qZUQvREl2U3JQMnMKLT4gaiRFLWdyZWFzZQpGUGw1UjYvbXh1TXQrUThuT3cKLS0tIDIxeWQvaW01RDgybmpPK0tCOXZMUkRTRTNJQlJtWi8vZ2lya3h2QkptNmMKsYSwAljILCRNNhem5i0PClYkhXkJa5cg5/LtZKZNGUIETxYu5IrVDTWhAHKNxHk=" }
GITLAB_TOKEN= { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBseng5eEFRVE1BQXVUaEF4YkRpSzJGUlY1QjNGWWVjblMvMW1YcmJZUzNJCnBDT2xyZlBZSHNuQlIrUFZkZUJiYjNzUGZudmhoVHhEU1pOTWgzMndlajgKLT4gdC1ncmVhc2UgRyA/X1gkIDx+ZncKbFlJTjdQZ3dxcVpCWjNqb1dNQkY2RWlpM3pIZEhneGcwUVUvTHQrUVhGc0MrWVRxMFJRMlpoandyakpWCi0tLSBrcXBRTlI5dWpvVVF5dW00QlF5N2FsdmlWRFJjUUMvMlFXdWdLZlZPRjFjCpe2FbUOTV4RP9IPiSpfbCCtYHSwAQL/bWLbVh3zyUYSVDwFyMSvB5Ph7iUgUsp72CgIS0Ug+jo4sfolKgIM1GBsZjcZWvDuGIkA2XyUKNz0RHXdTzj/xdKDyJ6Ov5I=" }
