default_provider = "age"

[providers.age]
type = "age"
recipients = ["age1y6z5twxvg2rv40j8q8323yke6scxrtewl8e92l5dkjm75z75cscshvgrgg"]

[secrets]
GITLAB_USERNAME= { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4REh3WTBOTG9rVGVFRDVUK1BORnU2elJhNkZ2RGw4YW5oazV5NVV5cEFjCmhGRk0rVW9oZUMvVEtVVDdwTjNRbEU1M2VBQTJIdG5qZUQvREl2U3JQMnMKLT4gaiRFLWdyZWFzZQpGUGw1UjYvbXh1TXQrUThuT3cKLS0tIDIxeWQvaW01RDgybmpPK0tCOXZMUkRTRTNJQlJtWi8vZ2lya3h2QkptNmMKsYSwAljILCRNNhem5i0PClYkhXkJa5cg5/LtZKZNGUIETxYu5IrVDTWhAHKNxHk=" }
GITLAB_TOKEN= { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvcmVUYW5MUWNkTURqalJvY1VtQkV4WWRGbDk2Z3IrKzhWbks0am5BVVhJCmF3WVJ6NVBXRWJSL3djUEZQSjR3UjQzcjNzLzREaEM2YmdQLzdERDBWVGcKLT4gJloiWlwwJ18tZ3JlYXNlIDVCOXcKY3FndEVPa0YxaW5nWFJKY3U0ZjRHRG1nTURkNDRVbk1YeXp5ZVNTQWQ3N0o2TEd3cG5OSHZHa3N2RXlaU1ZGUgpQUnkxV09VVEhUcHUKLS0tIGllR096MEV5bVgxQzZ6T0pRNC9sL1lwa0UwMUpvcWI4YXQxSktOckFjR0kKjlZ4qutoIxC2O8RynPVGCKfoNMZiCnClhaTP1f3UWbbftz+mzXjxEBDHSsKmHMEK/4mXYjjr0uVP8FP5q9qzC2GR9WaeuCtpfTDfJYiqFn5xiiFJe6eLHuOz7Gax+w==" }
